#!/bin/sh

CONFIG_FILE=./config.sh
CONFIG_FILE_TEMPLATE=./config.template.sh

if [ -f "$CONFIG_FILE" ]; then
  # If the config file exists, pull in the config variables
  . $CONFIG_FILE
else
  # If the config file does not exist, throw an error and exit
  echo "ERROR: No '$CONFIG_FILE' file exists."
  echo "Create a $CONFIG_FILE file based on $CONFIG_FILE_TEMPLATE"
  exit 1
fi

makeFileFromTemplate () {
eval "cat << EOF
# DO NOT EDIT THIS FILE!
# This file is generated automatically by $(readlink -f $0).
$(cat $1)
EOF
" > $2
}

# Create the docker-compose-base file
makeFileFromTemplate $DOCKER_COMPOSE_BASE_TEMPLATE $DOCKER_COMPOSE_BASE_FILE

# Create the docker-compose-dev file
makeFileFromTemplate $DOCKER_COMPOSE_DEV_TEMPLATE $DOCKER_COMPOSE_DEV_FILE

# Create the docker-compose-prod file
makeFileFromTemplate $DOCKER_COMPOSE_PROD_TEMPLATE $DOCKER_COMPOSE_PROD_FILE

# Create the dev Dockerfile for the node service
makeFileFromTemplate $NODE_DEV_DOCKERFILE_TEMPLATE $NODE_DEV_DOCKERFILE

# Create the prod Dockerfile for the node service
makeFileFromTemplate $NODE_PROD_DOCKERFILE_TEMPLATE $NODE_PROD_DOCKERFILE

# Create the .env file for the client part of the node service
makeFileFromTemplate $CLIENT_DOTENV_TEMPLATE $CLIENT_DOTENV_FILE
